// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_vsakfRJfF4XzTHcG8jsURGIzgZlPVY',
    appId: '1:43202346710:web:3e15e0db79ebff5beb5377',
    messagingSenderId: '43202346710',
    projectId: 'pastelaria-express',
    authDomain: 'pastelaria-express.firebaseapp.com',
    storageBucket: 'pastelaria-express.appspot.com',
    measurementId: 'G-21H2SGZHWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrecuQj2qnAww9XmC9Dn8bypiMKpEu-BQ',
    appId: '1:43202346710:android:91ec1515a818d297eb5377',
    messagingSenderId: '43202346710',
    projectId: 'pastelaria-express',
    storageBucket: 'pastelaria-express.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkngRuCDq6r_5Tns7WuVxBHCiYmrtiuHI',
    appId: '1:43202346710:ios:6ae0262a2134a58ceb5377',
    messagingSenderId: '43202346710',
    projectId: 'pastelaria-express',
    storageBucket: 'pastelaria-express.appspot.com',
    iosClientId: '43202346710-o4bb0i1llkfr3hsigaru2f1vc0m75th8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
